[phases.setup]
nixPkgs = ["python311", "poetry"]

[phases.install]
cmds = [
  "poetry config virtualenvs.create false",
  "poetry install --no-dev --no-interaction --no-ansi"
]

[phases.build]
cmds = [
  "poetry run alembic upgrade head"
]

[start]
cmd = "poetry run uvicorn main:app --host 0.0.0.0 --port $PORT"

